install.packages(c("testthat",
                   "rmarkdown",
                   "pkgdown",
                   "ggplot2",
                   "knitr",
                   "LPWC",
                   "devtools",
                   "fpc",
                   "reshape2"))
